### ISSUE TITLE
role: freeipa_server: msg: In unattended mode you need to provide at least -r, -p and -a options

### ISSUE THREAD

**Issue by bzblf** [Linuxfabrik/lfops#83]
When running the freeipa_server role `ansible-playbook --inventory <inventory> linuxfabrik.lfops.freeipa_server --tags freeipa_server`,  i get the error message below:
```

TASK [freeipa.ansible_freeipa.ipaserver : Install - Server installation test] *******************************************************************************************************************************
Monday 19 September 2022  14:34:47 +0200 (0:00:00.053)       0:00:02.725 ****** 
fatal: [<hostname>]: FAILED! => changed=false 
  msg: In unattended mode you need to provide at least -r, -p and -a options

```

**Comment by bzblf** [comment]
`Rocky Linux release 8.6 (Green Obsidian)`

**Comment by NavidSassan** [comment]
the specific freeipa error is caused by neither the domain nor the realm being set: https://github.com/freeipa/ansible-freeipa/issues/718.
lfops tries to use the `ansible_facts["domain"]` for the domain and realm. However determining `ansible_facts["domain"]` requires the DNS setup to be correct (which was not the case here). I will improve the lfops role to check for a proper DNS setup before calling the official freeipa role.
